spring.application.name=attendanceService
server.port=8093

# Base de datos (crear librodigital_attendance en fase de BD)
spring.datasource.url=jdbc:postgresql://localhost:5432/librodigital_attendance
spring.datasource.username=postgres
spring.datasource.password=monsalve1974

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

jwt.secret=librodigital2026SecretKeyForJWTTokenGenerationAndValidation12345

academic.service.url=http://localhost:8092
